wordpress_url: www.sdss.org
skyserver_release: None
dev:
  wordpress_url: testng.sdss.org
  skyserver_release: ""
base_url: "{{release}}.sdss.org"
title: "SDSS Splashpage"

sections:

  - id: portals
    title: Data Portals
    rows:
      - cards:
          - id: data
            header: Science Archive Server
            url: /sas/
            picture: sas
            overlay: Access SDSS images and spectra using the SAS filesystem

          - id: skyserver
            header: SkyServer
            external_url: https://skyserver.sdss.org/
            picture: skyserver.sdss.org
            overlay: Access SDSS catalog data through a web browser


  - id: epo
    title: Education/Public Outreach
    rows:
      - cards:
          - id: sdsshome
            header: SDSS Home
            external_url: https://www.sdss4.org/
            picture: sdss.org
            overlay: "The Sloan Digital Sky Survey home page: mapping the Universe in 3-D"

          - id: voyages
            header: SDSS Voyages
            external_url: http://voyages.sdss.org
            picture: voyages.sdss.org
            overlay: Customizable education resources

          - id: news
            header: SDSS Press Releases
            external_url: https://blog.sdss.org/
            picture: sdss_blog
            overlay: Follow the latest news on SDSS Blog


  - id: data
    title: Data Interaction
    rows:

      - cards:
          - id: imaging
            header: Imaging
            external_url: https://dr12.sdss.org/fields
            picture: imaging
            ext: .jpg
            overlay: Search SDSS imaging data

          - id: optical
            header: Optical Spectra
            url: /optical/
            picture: optical1
            overlay: Browse optical data

          - id: infrared
            header: Infrared Spectra
            url: /infrared/
            picture: infrared1
            overlay: Browse infrared data

      - cards:
          - id: marvin
            header: MaNGA Data with Marvin
            external_url: https://dr17.sdss.org/marvin/
            picture: manga_169_v3
            ext: .jpg
            overlay: Explore IFU spectroscopy data

          - id: mastar
            header: MaNGA Stellar Library
            external_url: https://dr17.sdss.org/mastar/
            picture: mastar
            overlay: High-quality stellar spectra
